export { default as Navbar } from '../components/Navbar'
export { default as Homepage } from '../components/Homepage'
export { default as Cryptocurrencies } from '../components/Cryptocurrencies'
export { default as Exchanges } from '../components/Exchanges'
export { default as CryptoDetails } from '../components/CryptoDetails'
export { default as News } from '../components/News'